package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"strconv"
	"user/internal/app/entity"
	"user/internal/transports/http/graphql/graph/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUser) (*model.User, error) {
	user, err := r.services.UserCreator().Store(input.FirstName, input.LastName, input.Email, input.Phone)

	if err != nil {
		return nil, err
	}

	return &model.User{
		ID:        strconv.FormatInt(user.ID, 10),
		FirstName: user.FirstName,
		LastName:  user.LastName,
		Email:     user.Email,
		Phone:     user.Phone,
	}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.services.UserProvider().ByCriteria(entity.UserFilter{})

	if err != nil {
		return nil, err
	}

	if len(users) == 0 {
		return nil, nil
	}

	result := make([]*model.User, 0, len(users))

	for _, user := range users {
		result = append(
			result,
			&model.User{
				ID:        strconv.FormatInt(user.ID, 10),
				FirstName: user.FirstName,
				LastName:  user.LastName,
				Email:     user.Email,
				Phone:     user.Phone,
			},
		)
	}

	return result, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	userId, err := strconv.ParseInt(id, 10, 64)

	if err != nil {
		return nil, err
	}

	users, err := r.services.UserProvider().ByCriteria(entity.UserFilter{ID: &userId})

	if err != nil {
		return nil, err
	}

	if len(users) == 0 {
		return nil, nil
	}

	user := users[0]

	return &model.User{
		ID:        strconv.FormatInt(user.ID, 10),
		FirstName: user.FirstName,
		LastName:  user.LastName,
		Email:     user.Email,
		Phone:     user.Phone,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
